### ISSUE TITLE
Need explanation for create_csv.py

### ISSUE THREAD

**Issue by icesonata** [jaexplorer/DSTG-BiVulD-Tool#1]
Hi,

I'm interested in the binary analysis of this project. However, I'm confused about the input and the expected output of the create_csv.py file.
What are the input and the expected output of the `create_csv.py`?
If the input of `create_csv.py` is binary code, how do you know if the line ends with a colon in the code?

Also, do you guys have a report or research paper, or documentation for this project?

Thanks in advance.

**Comment by jaexplorer** [comment]
Hi,
The input is a binary file. The output is a web interface that outlines at a binary level vunerabilities within functions.
You can map binary bytes to ASCII table to check for colons.

No we do not unfortunately. The machine learning element was carried offsite by another researcher and the model was given to us "model.h5" to which we would use to display the results.

**Comment by icesonata** [comment]
I tried inputting a binary file, e.g., `file_a.o`, to `create_csv.py` but it does not work as I thought. I got an error like the below:

```python
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
[<ipython-input-16-216bf95439cd>](https://localhost:8080/#) in <module>()
      7 asm = []
      8 
----> 9 for line in objdump:
     10         # Skip blank lines
     11         if len(line) > 1:

[/usr/lib/python3.7/codecs.py](https://localhost:8080/#) in decode(self, input, final)
    320         # decode input (taking the buffer into account)
    321         data = self.buffer + input
--> 322         (result, consumed) = self._buffer_decode(data, self.errors, final)
    323         # keep undecoded input until the next call
    324         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 32: invalid start byte
``` 

It seems that the error is due to reading the binary file in normal mode. I tried to read in binary file mode but ended up not data was extracted.
