### ISSUE TITLE
Any specific dependencies required?

### ISSUE THREAD

**Issue by icesonata** [jaexplorer/DSTG-BiVulD-Tool#2]
Hi,

Your project is interesting to me, and I want to reproduce your experiment. However, I'm having a tough time with the dependencies required to run the code. Do you still have list of dependencies of this project, e.g., a `requirements.txt` for BiVulD?

**Comment by jaexplorer** [comment]
No the project has been shelved, sorry to say. It only exists as a relic of the past.
